c_compiler:    # [win]
- vs2019       # [win]
cxx_compiler:  # [win]
- vs2019       # [win]


# It seems that there is a build error with GCC 11 and 12
# https://github.com/google/highway/issues/1570
# https://github.com/google/highway/commit/213fd6a06b290c4ed9cf4d5a26fdfc32e8a47aa8
# We are hitting an internal compiler error ....
c_compiler_version:     # [linux and ppc64le]
  - 10                  # [linux and ppc64le]
cxx_compiler_version:   # [linux and ppc64le]
  - 10                  # [linux and ppc64le]
