{% set name = "libhwy" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/highway/archive/refs/tags/{{ version }}.tar.gz
  sha256: faccd343935c9e98afd1016e9d20e0b8b89d908508d1af958496f8c2d3004ac2

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libhwy', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config            # [unix]
    - make                  # [unix]
    - ninja                 # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libhwy${SHLIB_EXT}             # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libhwy.pc            # [unix]
    - test -f ${PREFIX}/include/hwy/highway.h              # [unix]
    - test -f ${PREFIX}/include/hwy/contrib/dot/dot-inl.h  # [unix]
    - test -f ${PREFIX}/include/hwy/tests/hwy_gtest.h      # [unix]
    - if not exist %PREFIX%\\Library\\lib\\hwy.lib exit 1                           # [win]
    - if not exist %PREFIX%\\Library\\bin\\hwy.dll exit 1                           # [win]
    - if not exist %PREFIX%\\Library\\include\\hwy\\highway.h exit 1                # [win]
    - if not exist %PREFIX%\\Library\\include\\hwy\\contrib\\dot\\dot-inl.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\hwy\\tests\hwy_gtest.h  exit 1       # [win]
    - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\libhwy.pc exit 1              # [win]

about:
  home: https://github.com/google/highway
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Efficient and performance-portable vector software

extra:
  recipe-maintainers:
    - hmaarrfk
